backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

# Configuration des collections (contenu éditable)
collections:
  - name: "actualites"
    label: "Actualités"
    folder: "pages/actualites"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Publié", name: "published", widget: "boolean", default: true}

  - name: "adhesion"
    label: "Demandes d'adhésion"
    folder: "pages/adhesion"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Formulaire actif", name: "active", widget: "boolean", default: true}

# Configuration du site
site_url: "https://votre-site.netlify.app"
display_url: "https://votre-site.netlify.app"

