backend:
  name: git-gateway
  branch: main
  identity_url: "https://test8585.netlify.app/.netlify/identity"
  gateway_url: "https://test8585.netlify.app/.netlify/git"


media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "inscriptions"
    label: "Inscriptions Newsletter"
    folder: "data/inscriptions"
    create: true
    fields:
      - {label: "Prénom", name: "prenom", widget: "string"}
      - {label: "Nom", name: "nom", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Ville", name: "ville", widget: "string", required: false}
      - {label: "Newsletter", name: "newsletter", widget: "boolean", default: true}
      - {label: "Événements", name: "evenements", widget: "boolean", default: false}
      - {label: "Date d'inscription", name: "date_inscription", widget: "datetime"}
      - {label: "Statut", name: "statut", widget: "select", options: ["actif", "désinscrit", "en attente"], default: "actif"}

local_backend: true
