backend:
  name: git-gateway
  branch: main


media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "settings"
    label: "Paramètres du site"
    files:
      - name: "general"
        label: "Paramètres généraux"
        file: "data/settings/general.yml"
        fields:
          - {label: "Titre du site", name: "site_title", widget: "string", default: "La Nouvelle Voie"}
          - {label: "Sous-titre", name: "site_subtitle", widget: "string", default: "Ensemble, construisons l'avenir de notre société"}
          - {label: "Description", name: "site_description", widget: "text", default: "Site officiel de La Nouvelle Voie"}
          - {label: "Email de contact", name: "contact_email", widget: "string", default: "contact@lanouvellevoie.fr"}

  - name: "inscriptions"
    label: "Inscriptions Newsletter"
    folder: "data/inscriptions"
    create: true
    fields:
      - {label: "Prénom", name: "prenom", widget: "string"}
      - {label: "Nom", name: "nom", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Ville", name: "ville", widget: "string", required: false}
      - {label: "Newsletter", name: "newsletter", widget: "boolean", default: true}
      - {label: "Événements", name: "evenements", widget: "boolean", default: false}
      - {label: "Date d'inscription", name: "date_inscription", widget: "datetime"}
      - {label: "Statut", name: "statut", widget: "select", options: ["actif", "désinscrit", "en attente"], default: "actif"}

# Supprimé local_backend pour utiliser Netlify Identity
